{{- if .Values.duckdns.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: duckdns-update
  namespace: infra
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: duckdns-update
  namespace: infra
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: duckdns-update
subjects:
  - kind: ServiceAccount
    name: duckdns-update
    namespace: infra
{{- end }}
