apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-init-script
  namespace: {{ .Values.tenantName }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  initialize-keycloak-realm.sh: |
    {{- .Files.Get "scripts/initialize-keycloak-realm.sh" | nindent 4 }}
