apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-{{ .Values.gateway.namespace }}-to-{{ .Values.tenantName }}
  namespace: {{ .Values.tenantName }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
