apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.service.name }}-health-check
  namespace: {{ .Values.tenantName }}
  labels:
    {{- include "tenant.service.labels" . | nindent 4 }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.service.name }}
    namespace: {{ .Values.tenantName }}
  default:
    port: {{ .Values.service.port }}
    http:
      path: {{ .Values.service.healthCheck.path }}
      match:
        statusCodes:
          - start: 200
            end: 299
    interval: {{ .Values.service.healthCheck.interval }}
    timeout: {{ .Values.service.healthCheck.timeout }}
    unhealthyThreshold: {{ .Values.service.healthCheck.unhealthyThreshold }}
