spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/zachbugay/aks-designs.git
    targetRevision: HEAD

infraBase:
  kubeletIdentityClientId: ""
  keyVaultName: ""
  tenantId: ""

gateway:
  aksLbSubnetId: ""
  identityProviderHostname: ""
  duckdns:
    enabled: false
    hostnames: []
