apiVersion: v1
kind: ConfigMap
metadata:
  name: verify-secrets-script
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra-base.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  verify-secrets.sh: |
    {{- .Files.Get "scripts/verify-secrets.sh" | nindent 4 }}
