apiVersion: v1
kind: ServiceAccount
metadata:
  name: verify-secrets-sync
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra-base.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
