apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-sync
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra-base.secretsSync.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "infra-base.secretsSync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infra-base.secretsSync.labels" . | nindent 8 }}
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
            limits:
              cpu: 5m
              memory: 32Mi
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-tls-secrets
