apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-tls-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infra-base.secretProvider.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.kubeletIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: root-ca-cert
          objectType: secret
        - |
          objectName: gateway-tls-crt
          objectType: secret
        - |
          objectName: gateway-tls-key
          objectType: secret
        - |
          objectName: duckdns-token
          objectType: secret
  secretObjects:
    - secretName: duckdns-token
      type: Opaque
      data:
        - objectName: duckdns-token
          key: token
    - secretName: ca.bundle
      type: Opaque
      data:
        - objectName: root-ca-cert
          key: ca.crt
    - secretName: gateway-tls-secret
      type: kubernetes.io/tls
      data:
        - objectName: gateway-tls-crt
          key: tls.crt
        - objectName: gateway-tls-key
          key: tls.key
